from typing import List, Optional
from pydantic import BaseModel, Field

class YouTubeAnalysisResponse(BaseModel):
    title: str = Field(description="Title of the video")
    key_topics: List[str] = Field(description="Key topics covered in the video")
    summary: str = Field(description="Summary of the video")
    recommended_audience: str = Field(description="Recommended audience for the video")

class TranscriptRequest(BaseModel):
    url: str = Field(description="URL of the YouTube video to analyze")

class QuizQuestion(BaseModel):
    questions: str = Field(description="A question generated by the video transcript")
    options: Optional[str] = Field(description="4 answers for the question")
    correct_answer: str = Field(description="Correct Answer")

class QuizResponse(BaseModel):
    title: str
    questions: List[QuizQuestion]
